### ISSUE TITLE
fix icons name

### ISSUE THREAD

**Issue by Wercton** [russs123/Battle#1]
```
File "battle.py", line 46, in <module>
    panel_img = pygame.image.load('img/Icons/panel.png').convert_alpha()
FileNotFoundError: No such file or directory.
```
You named your image "Panel.png" instead of "panel.png".

Nice work, by the way. I enjoyed your video on YouTube.

**Comment by russs123** [comment]
Well spotted. It didn't throw an error for me so I never picked this up. Fixed!
